 const list =
[
   {label:"კომედია",id:876,url:"https://www.allmovie.com/images/genres/genre_comedy.jpg"},
   {label:"ანიმაცია",id:882,url:"https://i.imgur.com/OlLgfU5.png"},
   {label:"დეტექტივი",id:728,url:"https://i.imgur.com/75MVeHP.jpg"},
   {label:"ისტორიული",id:881,url:"https://i.imgur.com/SbLTTz7.jpg"},
    {label:"კრიმინალური",id:873,url:"https://i.imgur.com/uOj6L8L.jpg"},
    {label:"ბიოგრაფიული",id:965,url:"https://i.imgur.com/6rrHB49.jpg"},
    {label:"ფანტასტიკა",id:878,url:"https://i.imgur.com/YLq8x0g.jpg"},
    {label:"თრილერი",id:872,url:"https://i.imgur.com/J4Eh2Ay.jpg"},
    {label:"მისტიკა",id:874,url:"https://i.imgur.com/xmG3fiy.jpg"},
    {label:"საშინელებათა",id:890,url:"https://i.imgur.com/iA0Tblp.jpg"},
    {label:"ვესტერნი",id:884,url:"https://i.imgur.com/spCnyo7.jpg"},
    {label:"დრამა",id:875,url:"https://i.imgur.com/aRbnFAM.jpg"},
    {label:"მიუზიკლი",id:886,url:"https://i.imgur.com/WnZFoaI.jpg"},
    {label:"სპორტული",id:891,url:"https://i.imgur.com/rO8dOa0.jpg"},
    {label:"მძაფრ-სიუჟეტიანი",id:871,url:"https://i.imgur.com/dhbi3kO.jpg"},
    {label:"საომარი",id:888,url:"https://i.imgur.com/mnVucR8.jpg"},
    {label:"სათავგადასავლო",id:877,url:"https://i.imgur.com/rL0WMLA.jpg"},
    {label:"მოკლემეტრაჟიანი",id:963,url:"https://i.imgur.com/ncB8LPm.jpg"},
    {label:"რომანტიკული",id:893,url:"https://i.imgur.com/xMLEAqV.jpg"},
    {label:"ფენტეზი",id:887,url:"https://i.imgur.com/3lVFKNj.jpg"},
    {label:"საოჯახო",id:889,url:"https://i.imgur.com/4pK2FVE.jpg"}]; export default list;
